# Generated by Django 4.2 on 2023-07-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer_server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
