# Generated by Django 4.2 on 2023-07-14 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designer_server', '0002_imageupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageUpload',
        ),
    ]
