name: designer_server

on:
  push:
    tags:
      - ci/cd.**

jobs:
  test-lint:
    name: BUILD AND UNIT TEST
    runs-on: ubuntu-20.04
    steps:
#       - name: Login to Docker Hub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKERHUB_USER }}
#           password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Checkout
        uses: actions/checkout@v2
#       - name: Pull
#         run: docker-compose pull
      - name: Up
        run: docker-compose -f/ docker-compose.dev.yml up --build
      - name: Unit Test
        run : docker_compose -f/ docker-compose.dev.yml exec designer_backend coverage run manage.py test
      - name: Run Test Coverage
        run : docker_compose -f/ docker-compose.dev.yml exec designer_backend coverage report
      - name: Generate Coverage Result Html
        run : docker compose -f ./docker-compose.dev.yml exec designer_backend coverage html