name: designer_server

on: [push]

jobs:
  test-lint:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull
        run: docker-compose pull
      - name: wait
        run: docker-compose run designer_backend bash -c "
          chmod +x ./wait_for_it.sh
          && ./wait_for_it.sh postgresql:5432 --timeout=120
          && python manage.py collectstatic --noinput
          && python manage.py makemigrations
          && python manage.py makemigrations designer_server web
          && python manage.py migrate
          && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
